### ISSUE TITLE
PHP got crashed after latest Timezone package installation

### ISSUE THREAD

**Issue by erlandl4g** [php/pecl-datetime-timezonedb#6]
TimezoneDB was updated to version 2022.7
Soon after that PHP 8.1 crashed and produced core dump which I have passed through GDB. Hope it helps.

```

gdb /usr/bin/php CoreDump
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/php...
(No debugging symbols found in /usr/bin/php)

warning: Can't open file /dev/zero (deleted) during file-backed mapping note processing

warning: Can't open file /anon_hugepage (deleted) during file-backed mapping note processing

warning: Can't open file /usr/lib/php/20210902/timezonedb.so (deleted) during file-backed mapping note processing
[New LWP 1131009]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/php -C -q -d include_path=/usr/share/php -d date.timezone=UTC -d outpu'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  call_destructors (closure=closure@entry=0x55bf3f2df440) at ./elf/dl-close.c:129
129     ./elf/dl-close.c: No such file or directory.



  Id   Target Id                           Frame 
* 1    Thread 0x7fa56a077980 (LWP 1131009) call_destructors (closure=closure@entry=0x55bf3f2df440) at ./elf/dl-close.c:129

Thread 1 (Thread 0x7fa56a077980 (LWP 1131009)):
#0  call_destructors (closure=closure@entry=0x55bf3f2df440) at ./elf/dl-close.c:129
#1  0x00007fa56c280c85 in __GI__dl_catch_exception (exception=exception@entry=0x0, operate=operate@entry=0x7fa56cc08160 <call_destructors>, args=args@entry=0x55bf3f2df440) at ./elf/dl-error-skeleton.c:182
#2  0x00007fa56cc08636 in _dl_close_worker (force=force@entry=false, map=<optimized out>, map=<optimized out>) at ./elf/dl-close.c:292
#3  0x00007fa56cc092a2 in _dl_close_worker (force=false, map=0x55bf3f2df440) at ./elf/dl-close.c:150
#4  _dl_close (_map=0x55bf3f2df440) at ./elf/dl-close.c:818
#5  0x00007fa56c280c28 in __GI__dl_catch_exception (exception=exception@entry=0x7fffb6a87450, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:208
#6  0x00007fa56c280cf3 in __GI__dl_catch_error (objname=0x7fffb6a874a8, errstring=0x7fffb6a874b0, mallocedp=0x7fffb6a874a7, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:227
#7  0x00007fa56c19c1ae in _dlerror_run (operate=<optimized out>, args=<optimized out>) at ./dlfcn/dlerror.c:138
#8  0x00007fa56c19bed8 in __dlclose (handle=<optimized out>) at ./dlfcn/dlclose.c:31
#9  0x000055bf3d5b9140 in ?? ()
#10 0x000055bf3d5cca69 in zend_hash_graceful_reverse_destroy ()
#11 0x000055bf3d5ba4d7 in ?? ()
#12 0x000055bf3d555d92 in php_module_shutdown ()
#13 0x000055bf3d3fd829 in ?? ()
#14 0x00007fa56c135d90 in __libc_start_call_main (main=main@entry=0x55bf3d3fd430, argc=argc@entry=23, argv=argv@entry=0x7fffb6a87828) at ../sysdeps/nptl/libc_start_call_main.h:58
#15 0x00007fa56c135e40 in __libc_start_main_impl (main=0x55bf3d3fd430, argc=23, argv=0x7fffb6a87828, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffb6a87818) at ../csu/libc-start.c:392
#16 0x000055bf3d3fe965 in _start ()
#0  call_destructors (closure=closure@entry=0x55bf3f2df440) at ./elf/dl-close.c:129
        array = 0x7fa5665411f7 <timelib_timezone_db_data_external+347863>
        sz = <optimized out>
        map = 0x55bf3f2df440
#1  0x00007fa56c280c85 in __GI__dl_catch_exception (exception=exception@entry=0x0, operate=operate@entry=0x7fa56cc08160 <call_destructors>, args=args@entry=0x55bf3f2df440) at ./elf/dl-error-skeleton.c:182
        old = <optimized out>
        errcode = 21951
        c = {exception = 0x55bf3f2da250, errcode = 0x55bf3f2db250, env = {{__jmpbuf = {94279887076816, 94279887080656, 94279887081984, 140348462149440, 140348471118576, 94279887090752, 4294967298, -696}, __mask_was_saved = 2, __saved_mask = {__val = {8899425026619931904, 5, 8899425026619931904, 2, 18446744073709550920, 2, 72198330295808616, 140348471115840, 72057594037927936, 140736257878368, 140736257879616, 0, 134, 0, 4294967295, 140736257879616}}}}}
        old = <optimized out>
#2  0x00007fa56cc08636 in _dl_close_worker (force=force@entry=false, map=<optimized out>, map=<optimized out>) at ./elf/dl-close.c:292
        imap = 0x55bf3f2df440
        i = 133
        nsid = <optimized out>
        ns = <optimized out>
        any_tls = false
        nloaded = <optimized out>
        maps = 0x7fffb6a86e40
        idx = <optimized out>
        done_index = <optimized out>
        unload_any = false
        scope_mem_left = false
        unload_global = 0
        first_loaded = <optimized out>
        r = <optimized out>
        tls_free_start = <optimized out>
        tls_free_end = <optimized out>
        not_pending = not_pending
        pending = pending
        rerun = rerun
        dl_close_state = pending
        __PRETTY_FUNCTION__ = "_dl_close_worker"
#3  0x00007fa56cc092a2 in _dl_close_worker (force=false, map=0x55bf3f2df440) at ./elf/dl-close.c:150
        nsid = <optimized out>
        idx = <optimized out>
        unload_any = <optimized out>
        scope_mem_left = <optimized out>
        first_loaded = <optimized out>
        tls_free_end = <optimized out>
        ns = <optimized out>
        done_index = <optimized out>
        out = <optimized out>
        r = <optimized out>
        nloaded = <optimized out>
        unload_global = <optimized out>
        retry = <optimized out>
        any_tls = <optimized out>
        maps = <optimized out>
        tls_free_start = <optimized out>
        not_pending = not_pending
        pending = pending
        rerun = rerun
        dl_close_state = pending
        nsid = <optimized out>
        ns = <optimized out>
        retry = <optimized out>
        any_tls = <optimized out>
        nloaded = <optimized out>
        maps = <optimized out>
        idx = <optimized out>
        __PRETTY_FUNCTION__ = "_dl_close_worker"
        done_index = <optimized out>
        unload_any = <optimized out>
        scope_mem_left = <optimized out>
        unload_global = <optimized out>
        first_loaded = <optimized out>
        out = <optimized out>
        r = <optimized out>
        tls_free_start = <optimized out>
        tls_free_end = <optimized out>
        l = <optimized out>
        l = <optimized out>
        lp = <optimized out>
        j = <optimized out>
        jmap = <optimized out>
        i = <optimized out>
        imap = <optimized out>
        new_list = <optimized out>
        remain = <optimized out>
        removed_any = <optimized out>
        cnt = <optimized out>
        cnt = <optimized out>
        tmap = <optimized out>
        new_size = <optimized out>
        newp = <optimized out>
        old = <optimized out>
        cnt = <optimized out>
        tmap = <optimized out>
        ns_msl = <optimized out>
        i = <optimized out>
        j = <optimized out>
        cnt = <optimized out>
        __value = <optimized out>
        fsl = <optimized out>
        i = <optimized out>
        imap = <optimized out>
        lnp = <optimized out>
        tab = <optimized out>
        entries = <optimized out>
        idx = <optimized out>
        size = <optimized out>
        this = <optimized out>
        newgen = <optimized out>
#4  _dl_close (_map=0x55bf3f2df440) at ./elf/dl-close.c:818
        map = 0x55bf3f2df440
#5  0x00007fa56c280c28 in __GI__dl_catch_exception (exception=exception@entry=0x7fffb6a87450, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:208
        errcode = 0
        c = {exception = 0x7fffb6a87450, errcode = 0x7fffb6a8735c, env = {{__jmpbuf = {140736257881255, 3442802574894990241, -576, 94279887141936, 57, 94279859045472, 3442802574743995297, 3419076213758526369}, __mask_was_saved = 0, __saved_mask = {__val = {0, 0, 8899425026619931904, 0, 18446744073709550920, 2, 8899425026619931904, 1, 18446744073709550920, 2, 94279890360464, 3, 62, 0, 140348460045523, 140736257881276}}}}}
        old = 0x0
#6  0x00007fa56c280cf3 in __GI__dl_catch_error (objname=0x7fffb6a874a8, errstring=0x7fffb6a874b0, mallocedp=0x7fffb6a874a7, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:227
        exception = {objname = 0x0, errstring = 0x0, message_buffer = 0x0}
        errorcode = <optimized out>
#7  0x00007fa56c19c1ae in _dlerror_run (operate=<optimized out>, args=<optimized out>) at ./dlfcn/dlerror.c:138
        result = <optimized out>
        objname = 0x55bf3f2df980 "\250"
        errstring = 0x55bf3f2df980 "\250"
        malloced = true
        errcode = <optimized out>
#8  0x00007fa56c19bed8 in __dlclose (handle=<optimized out>) at ./dlfcn/dlclose.c:31
No locals.
#9  0x000055bf3d5b9140 in ?? ()
No symbol table info available.
#10 0x000055bf3d5cca69 in zend_hash_graceful_reverse_destroy ()
No symbol table info available.
#11 0x000055bf3d5ba4d7 in ?? ()
No symbol table info available.
#12 0x000055bf3d555d92 in php_module_shutdown ()
No symbol table info available.
#13 0x000055bf3d3fd829 in ?? ()
No symbol table info available.
#14 0x00007fa56c135d90 in __libc_start_call_main (main=main@entry=0x55bf3d3fd430, argc=argc@entry=23, argv=argv@entry=0x7fffb6a87828) at ../sysdeps/nptl/libc_start_call_main.h:58
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -3442958056711486559, 140736257882152, 94279854707760, 94279858441912, 140348471115840, 3442802574876115873, 3419076289498350497}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#15 0x00007fa56c135e40 in __libc_start_main_impl (main=0x55bf3d3fd430, argc=23, argv=0x7fffb6a87828, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffb6a87818) at ../csu/libc-start.c:392
No locals.
#16 0x000055bf3d3fe965 in _start ()
No symbol table info available.
array = 0x7fa5665411f7 <timelib_timezone_db_data_external+347863>
sz = <optimized out>
map = 0x55bf3f2df440


Fatal signal: Segmentation fault
----- Backtrace -----
Backtrace unavailable
---------------------
A fatal error internal to GDB has been detected, further
debugging is not possible.  GDB will now terminate.

This is a bug, please report it.  For instructions, see:
<https://www.gnu.org/software/gdb/bugs/>.

No core file now.

```

**Comment by derickr** [comment]
I can't reproduce this, and nothing really indicates that it is the timezone library that causes this, just that it was loaded when this crashed. I also can't see your whole command that started this file, nor any commands that you sent to GDB.

**Comment by erlandl4g** [comment]
I has happened only once, after TimeZone update attempt. Possible coincidence but nothing else was happening on the server except few hits,

**Comment by erlandl4g** [comment]
Seems like this is not a timezone issue but Apache2 or PHP 8.1 as I was installing phpredis and Apache2 crashed same way.
